#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[custom_plugins]]
  repo = "lilydjwg/colorizer"
  merged = false

# -- icons --
[[custom_plugins]]
  repo="ryanoasis/vim-devicons"
  merged=0

# -- theme --

[[layers]]
  name = "colorscheme"
  
##[options]
##  colorscheme = "tokyonight"
##  colorscheme_bg = "dark"


##[[custom_plugins]]
##  repo = "https://github.com/folke/tokyonight.nvim"
##  merged = 0

[[custom_plugins]]
  repo = "https://github.com/xiyaowong/nvim-transparent"
  merged = 0

# ------------------
#   -- Dev --
# ------------------

[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

# -- langs --
[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#html"
  emmet_leader_key = "<C-e>"
  emmet_filetyps = ['html']

[[layers]]
  name = 'lang#java'
  format_on_save = true

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#xml"

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[layers]]
  name = "lang#ruby"

  [[layers]]
  name = "sudo"

